# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-02 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='life',
            name='birthDate',
            field=models.DateField(verbose_name='Birth date'),
        ),
    ]
