# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-12 09:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0002_auto_20170302_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='life',
            name='id',
        ),
        migrations.RemoveField(
            model_name='preferences',
            name='id',
        ),
        migrations.AlterField(
            model_name='life',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
