# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-22 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0003_auto_20170312_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='facebookId',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='preferences',
            name='isFacebook',
            field=models.BooleanField(default=False),
        ),
    ]
